config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'users#index'
  get  'users/help'
  get  'users/about'
  get  'users/contact'
  get 'session/new'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'fetch_long_url', to: 'urls#fetch_long_url'
  get 'show_long_url', to: 'urls#show_long_url'
  get 'urls/search'
  post 'urls/search_result'
  get 'urls/report'
  resources :users  
  resources :sessions
  resources :urls
  

  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
end

app/models/url.rb
class Url < ApplicationRecord
  
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name([Rails.env,base_class.to_s.pluralize.underscore].join('_'))
  
  VALID_LONG_URL_REGEX = /\A((http|https):\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?\Z/ix
  validates :long_url, presence: true, length: { maximum: 255 }, format: { with: VALID_LONG_URL_REGEX }
  #uniqueness: { case_sensitive: false }
  validates :domain,  presence: true, length: { maximum: 25 }
  validates :short_url,  presence: true, length: { maximum: 25 }

  before_save { self.long_url = long_url.downcase }
  
  after_create :start
  
  settings index: {
    number_of_shards: 1,
    number_of_replicas: 0,
    analysis: {
      analyzer: {
        pattern: {
          type: 'pattern',
          pattern: "\\s|_|-|\\.",
          lowercase: true
        },
        trigram: {
          tokenizer: 'trigram'
        }
      },
      tokenizer: {
        trigram: {
          type: 'ngram',
          min_gram: 3,
          max_gram: 1000,
          token_chars: ['letter', 'digit']
        }
      }
  } } do
    mapping do
      indexes :short_url, type: 'text', analyzer: 'english' do
        indexes :keyword, analyzer: 'keyword'
        indexes :pattern, analyzer: 'pattern'
        indexes :trigram, analyzer: 'trigram'
      end
      indexes :long_url, type: 'text', analyzer: 'english' do
        indexes :keyword, analyzer: 'keyword'
        indexes :pattern, analyzer: 'pattern'
        indexes :trigram, analyzer: 'trigram'
      end
    end
  end

  def self.custom_search(params)
    field = params[:field]+".trigram"
    query = params[:keyword]
    urls = self.__elasticsearch__.search(
    {
      query: {
        bool: {
          must: [{
            term: {
              "#{field}":"#{query}"
            }
          }]
        }
      }
    }).records
    return urls
  end

  def start
    CounterWorker.perform_async
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  skip_before_action :verify_authenticity_token
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls <br />
  **Authentication Required:** yes <br />
=end
  def index
    if session[:user_id] == nil
      redirect_to signup_path
      return
    end
  end
=begin
  **Common Name:** Create shorturl from the input longurl and domain
  **End points:** Other services
  **Request Type:** POST
  **Route:** urls_path
  **url:**  URI("http://localhost:3000/urls/new")
  **Paramas:** { "long_url" : " ",
            "domain"  : " "
          }
  **Cookies:** {
    Name : URL-Shortener
    Value : 
    Domain : localhost
    HttpOnly : True
    Secure : false
  }
  **Content-Type:** application/json; charset=utf-8
  **Input Type:** JSON
  **Input Fields:** longurl,domain 
  **Output Type:** JSON
  **Output Fields:** status, shorturl
  **Host:** localhost:3000
  **Cache-Control:** no-cache
  **Custom Status Messages:** {
    a)Message : "already_exist"
    Status  : 200 OK
    Description : If the input longurl already exists in the database,
    it will just find the shorturl correponding to that longurl in the database and 
    return that shorturl along with above mentioned message.
    b)Message  : "new created shorturl"
    Status   :  200 OK
    Description : If the input longurl is not already present in the database,
    and new shorturl is created correponding to that longurl and domain.
    It is than saved in the database and return the newly generated shorturl alongwith the above message.
    c)Message : "error occured"
    Status : 200 OK
    Description : If the input url is not according to the validations mentioned in the url model,
    than an error message will be displayed to the user as mentioned above
    d)Status : 404 Internal server error
    Description : If the longurl is not defined in the input params
    e)Message : "Short Domain not found,please add short domain" 
    Status : 404 OK
    Description : if domain entered by user in not in shortdomain table
  }   
=end
  def new
    if session[:user_id] == nil
      redirect_to signup_path
      return
    end
    @url = Url.new
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** POST <br />
  **Route :** /urls/create <br />
  **Authentication Required:** yes <br />
=end
  def create
    if session[:user_id] == nil
      redirect_to signup_path
    end
    @url = Url.new(url_params)
    require 'digest/md5'
    @domain = Domain.find_by(domain_name: params[:url][:domain].downcase)
    if @domain.present?
      @check = Url.find_by(long_url: params[:url][:long_url])
      if @check.present?
        flash[:danger] = "Long Url already present."
        redirect_to @check
        return
      else
        short_domain = @domain.short_domain
        @url.url_digest = Digest::MD5.hexdigest(params[:url][:long_url])
        @url.short_url = short_domain + '/' + @url.url_digest[0,6]
        @url.count = 0
      end
    else
      flash[:danger] = "Ask admin to update Domain table"
      render 'new'
      return
    end
    respond_to do |format| 
      if @url.save
        format.html {redirect_to @url}
        format.json {render json: {"Short url" => @url.short_url}}
      else
        format.html{render 'new',:status=>404}
        format.json{render json:{"response" => "Invalid Url"},:status=>404}
      end
    end
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls/show <br />
  **Authentication Required:** yes <br />
=end
  def show
    if session[:user_id] == nil
      redirect_to signup_path
    end
    @url = Url.find(params[:id])
  end
=begin
  **Common Name:**Search for longurl from input shorturl
  **End points:** Other services
  **Request Type** : GET
  **Routes** : fetch_long_url_path
  **url:** URI("http://localhost:3000/fetch_long_url")
  **Params:** KEY->short_url , VALUE-> '' , DESCRIPTION-> 'ShortUrl Input to get longurl in return'
  **Cookies:**{
    Name : URL-Shortener
    Value : 
    Domain : localhost
    HttpOnly : True
    Secure : false
  }
  **Content-Type:** application/json; charset=utf-8
  **Output Type:** JSON
  **Output Fields:** status,longurl
  **Host:** localhost:3000
  **Cache-Control:**  no-cache
  **Custom Status Messages:**{
    a)Message : "longurl corresponding to shorturl is found"
    Status  : 200 OK
    Description : Since the input shorturl is already existed in the database,
    it will just find the longurl correponding to that shorturl in the database and 
    return that longurl along with above mentioned message.
    b)Message  : "Invalid shorturl"
    Status   :  404 OK
    Description : If the input shorturl is not already present in the database,
    it will return the above message
    c)Status : 500 Internal server error
    Description : If the shorturl key is not mentioned in the input params
  }
=end
  def fetch_long_url
    if session[:user_id] == nil
      redirect_to signup_path
      return
    end
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls/show_long_url <br />
  **Authentication Required:** yes <br />
=end
  def show_long_url
    if session[:user_id] == nil
      redirect_to signup_path
    end
    respond_to do |format|
      #@url = Url.find_by(short_url: params[:url][:short_url])
      @url = Rails.cache.fetch(params[:url][:short_url], expires_in: 15.minutes) do 
        Url.where(short_url: params[:url][:short_url]).first
      end
      if @url.present?
        HitcountWorker.perform_async(@url.id)
        format.html{redirect_to @url}
        format.json{render json:{"long_url"=>@url.long_url}}
      else
        flash[:danger] = "Short URL not found"
        format.html{render :fetch_long_url,:status=>404}
        format.json{render json:{"response"=>"Not Found"},:status=>404}
      end  
    end
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls/search <br />
  **Authentication Required:** yes <br />
=end
  def search
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls/search_result <br />
  **Authentication Required:** yes <br />
=end
  def search_result
    if params[:url][:keyword].nil?
      @urls = []
    else
      @urls = Url.custom_search(params[:url])
    end
  end
=begin
  **Author:** Shobhit Upadhyay <br/>
  **Common Name:** URL Shortener <br />
  **Request Type:** GET <br />
  **Route :** /urls/report <br />
  **Authentication Required:** yes <br />
=end
  def report
    @conversions = Conversion.all
  end

  private
    def url_params
      params.require(:url).permit(:long_url, :domain)
    end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/fetch_long_url.html.erb
<% provide(:title, "Get long URL") %>
<h1>Get long URL</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:url, url: show_long_url_path,method: :get) do |f| %>
      <%= f.label :short_url %>
      <%= f.text_field :short_url, class: 'form-control' %>

      <%= f.submit "Get Long URL", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/urls/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="w3-container">
      <h1>
        <br>
        What do you want to do
      </h1>
      <h2>
        <a href="http://0.0.0.0:3000/urls/new" class="w3-button w3-black w3-border w3-hover-dark-grey">Get Short URL from Long URL</a>
        <br>
        or
        <br>
        <a href="http://0.0.0.0:3000/fetch_long_url" class="w3-button w3-black w3-border w3-hover-dark-grey">Get Long URL from Short URL</a>
      </h2>
    </div>
  </body>
</html>

app/views/urls/new.html.erb
<% provide(:title, "URL Shortener") %>
<h1>URL Shortener</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:url, url: urls_path) do |f| %>
    <%= render 'shared/error_msg' %>

      <%= f.label :long_url %>
      <%= f.text_field :long_url, class: 'form-control' %>

      <%= f.label :domain %>
      <%= f.text_field :domain, class: 'form-control' %>

      <%= f.submit "Create Short URL", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/urls/report.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Count</th>
    </tr>
  </thead>
  <% @conversions.each do |t| %>
  <thread>
    <tr>
      <td><%= t.date %></td>
      <td><%=t.count%></td>
    </tr>
  <%end%>
  </thread>
</table>

app/views/urls/search.html.erb
<% provide(:title, "Search") %>
<h1>Search</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:url, url: urls_search_result_path) do |f| %>
    
      <%= f.label :keyword %>
      <%= f.select :field, ['long_url', 'short_url']%>
      <%= f.text_field :keyword, class: 'form-control' %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/urls/search_result.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Long Url</th>
      <th>Short Url</th>
      <th>Domain</th>
    </tr>
  </thead>
  <% @urls.each do |t| %>
  <thread>
    <tr>
      <td><%= t.long_url %></td>
      <td><%=t.short_url%></td>
      <td><%=t.domain%></td>
    </tr>
    <%end%>
  </thread>
</table>

app/views/urls/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Long Url</div>
        <div class="panel-body"><%= @url.long_url %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Domain</div>
        <div class="panel-body"><%= @url.domain %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Short Url</div>
        <div class="panel-body"><%= @url.short_url %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Hit Count</div>
        <div class="panel-body"><%= @url.count %></div>
      </div>
    </div>
  </div>
  <h2>
  <a href="http://0.0.0.0:3000/urls/new" class="w3-button w3-black w3-border w3-hover-dark-grey">Get Short URL from Long URL</a>
  <a href="http://0.0.0.0:3000/fetch_long_url" class="w3-button w3-black w3-border w3-hover-dark-grey">Get Long URL from Short URL</a>
  </h2>
  <p> Today's total conversions
  <% @conversion = Conversion.find_by(date: Date.today) %> 
  <%= "#{@conversion.count}" %>
  </p>
</div>

app/views/urls/show_long_url.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Long Url</div>
        <div class="panel-body"><%= @url.long_url %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Domain</div>
        <div class="panel-body"><%= @url.domain %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Short Url</div>
        <div class="panel-body"><%= @url.short_url %></div>
      </div>
      <div class="panel panel-primary">
        <div class="panel-heading">Hit Count</div>
        <div class="panel-body"><%= @url.count %></div>
      </div>
    </div>
  </div>
  <a href="http://0.0.0.0:3000/urls/home" class="w3-button w3-indigo w3-border w3-hover-indigo"><h1>Try Again</h1></a>

  <p> Today's total conversions
  <% @conversion = Conversion.find_by(date: Date.today) %> 
  <%= "#{@conversion.count}" %>
  </p>
</div>