config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  root 'users#index'
  get  'users/help'
  get  'users/about'
  get  'users/contact'
  get 'session/new'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'fetch_long_url', to: 'urls#fetch_long_url'
  get 'show_long_url', to: 'urls#show_long_url'
  get 'urls/search'
  post 'urls/search_result'
  get 'urls/report'
  resources :users  
  resources :sessions
  resources :urls
  

  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://guides.rubyonrails.org//">Ruby on Rails Guide</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   users_about_path %></li>
      <li><%= link_to "Contact", 'https://www.facebook.com/shobhit.upadhyay.376' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "URL Shortener", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Daily Report", urls_report_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Search", urls_search_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>